// Next.js API route voor individuele projecten
import { NextRequest, NextResponse } from 'next/server';

// Mock data - dit zou normaal uit een database komen
const projectData = [
  {
    projectNumber: "PROJ-001",
    projectName: "Nieuwbouw Woningen De Vliert",
    projectLeader: "Jan van der Berg",
    projectType: "Nieuwe aanleg",
    location: "De Vliert, Den Haag",
    groundOwnership: "Openbaar (overheid)",
    workDescription: "Aanleg van nieuwe woningen met duurzame energievoorziening",
    client: "Gemeente Den Haag",
    clientName: "Gemeente Den Haag",
    contactPerson: "Marieke Jansen",
    phoneNumber: "070-1234567",
    email: "marieke.jansen@denhaag.nl",
    address: "Spui 70, 2511 BT Den Haag",
    applicationNumber: "APP-2024-001",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: false,
    archaeologyResearch: true,
    ngeReport: false,
    apartments: 24,
    apartmentsArea: 2400,
    rowHouses: 12,
    rowHousesArea: 1800,
    twoUnderOneRoof: 8,
    twoUnderOneRoofArea: 1200,
    detachedHouses: 4,
    detachedHousesArea: 800,
    commercialSpaces: 2,
    commercialSpacesArea: 300,
    generalSpaces: 1,
    generalSpacesArea: 150,
    contaminatedGround: "Nee, rapport opvragen",
    fireHydrants: "Ja",
    connectionType1: 3,
    connectionType2: 2,
    connectionType3: 1,
    totalSolarPanels: 120,
    totalInverterPower: 48000,
    totalPrivateChargingStations: 48,
    totalPublicChargingStations: 4,
    totalHeatPumps: 48,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "NVT"
  },
  {
    projectNumber: "PROJ-002",
    projectName: "Renovatie Wijk Centrum",
    projectLeader: "Lisa de Vries",
    projectType: "Reconstructie",
    location: "Centrum, Amsterdam",
    groundOwnership: "Particulier",
    workDescription: "Reconstructie van bestaande wijk met duurzame verbeteringen",
    client: "Woningcorporatie Amsterdam",
    clientName: "Woningcorporatie Amsterdam",
    contactPerson: "Peter Bakker",
    phoneNumber: "020-9876543",
    email: "peter.bakker@woningcorporatie.nl",
    address: "Damrak 1, 1012 LP Amsterdam",
    applicationNumber: "APP-2024-002",
    designPlan: true,
    trackDrawing: false,
    soilData: false,
    natura2000Report: false,
    archaeologyResearch: false,
    ngeReport: true,
    apartments: 36,
    apartmentsArea: 3600,
    rowHouses: 18,
    rowHousesArea: 2700,
    twoUnderOneRoof: 0,
    twoUnderOneRoofArea: 0,
    detachedHouses: 0,
    detachedHousesArea: 0,
    commercialSpaces: 4,
    commercialSpacesArea: 600,
    generalSpaces: 2,
    generalSpacesArea: 300,
    contaminatedGround: "Ja",
    fireHydrants: "Nee",
    connectionType1: 2,
    connectionType2: 3,
    connectionType3: 0,
    totalSolarPanels: 180,
    totalInverterPower: 72000,
    totalPrivateChargingStations: 54,
    totalPublicChargingStations: 6,
    totalHeatPumps: 54,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "Woningen"
  },
  {
    projectNumber: "PROJ-003",
    projectName: "Duurzame Wijk Watergraafsmeer",
    projectLeader: "Erik van Dijk",
    projectType: "Nieuwe aanleg",
    location: "Watergraafsmeer, Amsterdam",
    groundOwnership: "Openbaar (overheid)",
    workDescription: "Ontwikkeling van duurzame woonwijk met energieneutrale woningen",
    client: "Gemeente Amsterdam",
    clientName: "Gemeente Amsterdam",
    contactPerson: "Sandra Mulder",
    phoneNumber: "020-5551234",
    email: "sandra.mulder@amsterdam.nl",
    address: "Amstel 1, 1011 PN Amsterdam",
    applicationNumber: "APP-2024-003",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: true,
    archaeologyResearch: true,
    ngeReport: false,
    apartments: 48,
    apartmentsArea: 4800,
    rowHouses: 24,
    rowHousesArea: 3600,
    twoUnderOneRoof: 12,
    twoUnderOneRoofArea: 1800,
    detachedHouses: 8,
    detachedHousesArea: 1600,
    commercialSpaces: 6,
    commercialSpacesArea: 900,
    generalSpaces: 3,
    generalSpacesArea: 450,
    contaminatedGround: "Nee, rapport opvragen",
    fireHydrants: "Ja",
    connectionType1: 4,
    connectionType2: 3,
    connectionType3: 2,
    totalSolarPanels: 240,
    totalInverterPower: 96000,
    totalPrivateChargingStations: 92,
    totalPublicChargingStations: 8,
    totalHeatPumps: 92,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "NVT"
  },
  {
    projectNumber: "PROJ-004",
    projectName: "Herstructurering Oud-Zuid",
    projectLeader: "Marianne Smit",
    projectType: "Reconstructie",
    location: "Oud-Zuid, Rotterdam",
    groundOwnership: "Particulier",
    workDescription: "Herstructurering van bestaande wijk met focus op duurzaamheid",
    client: "Woningcorporatie Rotterdam",
    clientName: "Woningcorporatie Rotterdam",
    contactPerson: "Rob van der Laan",
    phoneNumber: "010-1234567",
    email: "rob.vanderlaan@woningcorporatie.nl",
    address: "Coolsingel 40, 3011 AD Rotterdam",
    applicationNumber: "APP-2024-004",
    designPlan: true,
    trackDrawing: true,
    soilData: false,
    natura2000Report: false,
    archaeologyResearch: false,
    ngeReport: true,
    apartments: 30,
    apartmentsArea: 3000,
    rowHouses: 15,
    rowHousesArea: 2250,
    twoUnderOneRoof: 6,
    twoUnderOneRoofArea: 900,
    detachedHouses: 3,
    detachedHousesArea: 600,
    commercialSpaces: 3,
    commercialSpacesArea: 450,
    generalSpaces: 2,
    generalSpacesArea: 300,
    contaminatedGround: "Ja",
    fireHydrants: "Ja",
    connectionType1: 2,
    connectionType2: 2,
    connectionType3: 1,
    totalSolarPanels: 150,
    totalInverterPower: 60000,
    totalPrivateChargingStations: 54,
    totalPublicChargingStations: 5,
    totalHeatPumps: 54,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "Woningen"
  },
  {
    projectNumber: "PROJ-005",
    projectName: "Energieneutrale Wijk Leidsche Rijn",
    projectLeader: "Tom de Jong",
    projectType: "Nieuwe aanleg",
    location: "Leidsche Rijn, Utrecht",
    groundOwnership: "Openbaar (overheid)",
    workDescription: "Ontwikkeling van energieneutrale woonwijk met smart grid technologie",
    client: "Gemeente Utrecht",
    clientName: "Gemeente Utrecht",
    contactPerson: "Linda van Beek",
    phoneNumber: "030-9876543",
    email: "linda.vanbeek@utrecht.nl",
    address: "Stadhuisbrug 1, 3511 LZ Utrecht",
    applicationNumber: "APP-2024-005",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: true,
    archaeologyResearch: true,
    ngeReport: false,
    apartments: 60,
    apartmentsArea: 6000,
    rowHouses: 30,
    rowHousesArea: 4500,
    twoUnderOneRoof: 15,
    twoUnderOneRoofArea: 2250,
    detachedHouses: 10,
    detachedHousesArea: 2000,
    commercialSpaces: 8,
    commercialSpacesArea: 1200,
    generalSpaces: 4,
    generalSpacesArea: 600,
    contaminatedGround: "Nee, rapport opvragen",
    fireHydrants: "Ja",
    connectionType1: 5,
    connectionType2: 4,
    connectionType3: 3,
    totalSolarPanels: 300,
    totalInverterPower: 120000,
    totalPrivateChargingStations: 115,
    totalPublicChargingStations: 10,
    totalHeatPumps: 115,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "NVT"
  },
  {
    projectNumber: "PROJ-006",
    projectName: "Transformatie Havenkwartier",
    projectLeader: "Annelies Bakker",
    projectType: "Reconstructie",
    location: "Havenkwartier, Den Haag",
    groundOwnership: "Particulier",
    workDescription: "Transformatie van industrieel gebied naar gemengde woonwijk",
    client: "Ontwikkelaar Havenkwartier BV",
    clientName: "Ontwikkelaar Havenkwartier BV",
    contactPerson: "Mark van der Meer",
    phoneNumber: "070-5559876",
    email: "mark.vandermeer@havenkwartier.nl",
    address: "Havenweg 123, 2586 AM Den Haag",
    applicationNumber: "APP-2024-006",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: false,
    archaeologyResearch: true,
    ngeReport: true,
    apartments: 42,
    apartmentsArea: 4200,
    rowHouses: 21,
    rowHousesArea: 3150,
    twoUnderOneRoof: 9,
    twoUnderOneRoofArea: 1350,
    detachedHouses: 6,
    detachedHousesArea: 1200,
    commercialSpaces: 5,
    commercialSpacesArea: 750,
    generalSpaces: 3,
    generalSpacesArea: 450,
    contaminatedGround: "Ja",
    fireHydrants: "Ja",
    connectionType1: 3,
    connectionType2: 3,
    connectionType3: 2,
    totalSolarPanels: 210,
    totalInverterPower: 84000,
    totalPrivateChargingStations: 78,
    totalPublicChargingStations: 7,
    totalHeatPumps: 78,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "Woningen"
  },
  {
    projectNumber: "PROJ-007",
    projectName: "Circulaire Wijk Stadspark",
    projectLeader: "Femke van der Berg",
    projectType: "Nieuwe aanleg",
    location: "Stadspark, Groningen",
    groundOwnership: "Openbaar (overheid)",
    workDescription: "Ontwikkeling van circulaire woonwijk met hergebruik van materialen",
    client: "Gemeente Groningen",
    clientName: "Gemeente Groningen",
    contactPerson: "Jeroen van der Wal",
    phoneNumber: "050-1234567",
    email: "jeroen.vanderwal@groningen.nl",
    address: "Grote Markt 1, 9712 HV Groningen",
    applicationNumber: "APP-2024-007",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: true,
    archaeologyResearch: true,
    ngeReport: false,
    apartments: 36,
    apartmentsArea: 3600,
    rowHouses: 18,
    rowHousesArea: 2700,
    twoUnderOneRoof: 9,
    twoUnderOneRoofArea: 1350,
    detachedHouses: 6,
    detachedHousesArea: 1200,
    commercialSpaces: 4,
    commercialSpacesArea: 600,
    generalSpaces: 2,
    generalSpacesArea: 300,
    contaminatedGround: "Nee, rapport opvragen",
    fireHydrants: "Ja",
    connectionType1: 3,
    connectionType2: 2,
    connectionType3: 1,
    totalSolarPanels: 180,
    totalInverterPower: 72000,
    totalPrivateChargingStations: 69,
    totalPublicChargingStations: 6,
    totalHeatPumps: 69,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "NVT"
  },
  {
    projectNumber: "PROJ-008",
    projectName: "Smart City Wijk Brainport",
    projectLeader: "Daan van der Heijden",
    projectType: "Nieuwe aanleg",
    location: "Brainport, Eindhoven",
    groundOwnership: "Openbaar (overheid)",
    workDescription: "Ontwikkeling van smart city woonwijk met IoT en duurzame technologie",
    client: "Gemeente Eindhoven",
    clientName: "Gemeente Eindhoven",
    contactPerson: "Sophie van der Ven",
    phoneNumber: "040-9876543",
    email: "sophie.vanderven@eindhoven.nl",
    address: "Stadhuisplein 1, 5611 EM Eindhoven",
    applicationNumber: "APP-2024-008",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: false,
    archaeologyResearch: true,
    ngeReport: false,
    apartments: 54,
    apartmentsArea: 5400,
    rowHouses: 27,
    rowHousesArea: 4050,
    twoUnderOneRoof: 12,
    twoUnderOneRoofArea: 1800,
    detachedHouses: 8,
    detachedHousesArea: 1600,
    commercialSpaces: 6,
    commercialSpacesArea: 900,
    generalSpaces: 3,
    generalSpacesArea: 450,
    contaminatedGround: "Nee, rapport opvragen",
    fireHydrants: "Ja",
    connectionType1: 4,
    connectionType2: 3,
    connectionType3: 2,
    totalSolarPanels: 270,
    totalInverterPower: 108000,
    totalPrivateChargingStations: 101,
    totalPublicChargingStations: 9,
    totalHeatPumps: 101,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "NVT"
  },
  {
    projectNumber: "PROJ-009",
    projectName: "Natuurinclusieve Wijk Groene Vallei",
    projectLeader: "Lotte van der Meer",
    projectType: "Nieuwe aanleg",
    location: "Groene Vallei, Nijmegen",
    groundOwnership: "Openbaar (overheid)",
    workDescription: "Ontwikkeling van natuurinclusieve woonwijk met groene daken en biodiversiteit",
    client: "Gemeente Nijmegen",
    clientName: "Gemeente Nijmegen",
    contactPerson: "Bas van der Pol",
    phoneNumber: "024-1234567",
    email: "bas.vanderpol@nijmegen.nl",
    address: "Burchtstraat 1, 6511 RA Nijmegen",
    applicationNumber: "APP-2024-009",
    designPlan: true,
    trackDrawing: true,
    soilData: true,
    natura2000Report: true,
    archaeologyResearch: true,
    ngeReport: false,
    apartments: 48,
    apartmentsArea: 4800,
    rowHouses: 24,
    rowHousesArea: 3600,
    twoUnderOneRoof: 12,
    twoUnderOneRoofArea: 1800,
    detachedHouses: 8,
    detachedHousesArea: 1600,
    commercialSpaces: 5,
    commercialSpacesArea: 750,
    generalSpaces: 3,
    generalSpacesArea: 450,
    contaminatedGround: "Nee, rapport opvragen",
    fireHydrants: "Ja",
    connectionType1: 4,
    connectionType2: 3,
    connectionType3: 2,
    totalSolarPanels: 240,
    totalInverterPower: 96000,
    totalPrivateChargingStations: 92,
    totalPublicChargingStations: 8,
    totalHeatPumps: 92,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "NVT"
  },
  {
    projectNumber: "PROJ-010",
    projectName: "Herontwikkeling Stationsgebied",
    projectLeader: "Rick van der Zee",
    projectType: "Reconstructie",
    location: "Stationsgebied, Tilburg",
    groundOwnership: "Particulier",
    workDescription: "Herontwikkeling van stationsgebied tot gemengde woon-werkwijk",
    client: "Ontwikkelaar Stationsgebied BV",
    clientName: "Ontwikkelaar Stationsgebied BV",
    contactPerson: "Nina van der Berg",
    phoneNumber: "013-5551234",
    email: "nina.vanderberg@stationsgebied.nl",
    address: "Spoorlaan 456, 5038 CB Tilburg",
    applicationNumber: "APP-2024-010",
    designPlan: true,
    trackDrawing: true,
    soilData: false,
    natura2000Report: false,
    archaeologyResearch: false,
    ngeReport: true,
    apartments: 66,
    apartmentsArea: 6600,
    rowHouses: 33,
    rowHousesArea: 4950,
    twoUnderOneRoof: 15,
    twoUnderOneRoofArea: 2250,
    detachedHouses: 10,
    detachedHousesArea: 2000,
    commercialSpaces: 10,
    commercialSpacesArea: 1500,
    generalSpaces: 5,
    generalSpacesArea: 750,
    contaminatedGround: "Ja",
    fireHydrants: "Ja",
    connectionType1: 5,
    connectionType2: 4,
    connectionType3: 3,
    totalSolarPanels: 330,
    totalInverterPower: 132000,
    totalPrivateChargingStations: 124,
    totalPublicChargingStations: 11,
    totalHeatPumps: 124,
    pvOnCvzConnection: "CVZ",
    largeConsumptionConnection: "Woningen"
  }
];

export async function GET(
  request: NextRequest,
  { params }: { params: { projectNumber: string } }
) {
  try {
    const { projectNumber } = params;
    const project = projectData.find(p => p.projectNumber === projectNumber);
    
    if (!project) {
      return NextResponse.json({
        success: false,
        error: 'Project not found'
      }, { status: 404 });
    }
    
    return NextResponse.json({
      success: true,
      data: project
    });
  } catch (error) {
    console.error('Error fetching project:', error);
    return NextResponse.json({
      success: false,
      error: 'Failed to fetch project'
    }, { status: 500 });
  }
}
