// Next.js API route voor D2 formulieren
import { NextRequest, NextResponse } from 'next/server';

// Mock D2 form data
const d2FormData = [
  {
    projectNumber: "PROJ-001",
    projectName: "Nieuwbouw Woningen De Vliert",
    projectLeader: "Jan van der Berg",
    projectType: "Nieuwe aanleg",
    meetingDate: "2024-01-15",
    meetingLocation: "Gemeentehuis Den Haag",
    participatingUtilities: ["Stedin", "Evides", "Eneco"],
    otherParticipants: "Gemeente Den Haag, Architectenbureau",
    numberOfHouses: 24,
    numberOfApartments: 24,
    numberOfCommercialSpaces: 2,
    numberOfGeneralSpaces: 1,
    electricityReturn: true,
    largeConsumptionConnection: false,
    largeConsumptionValue: "",
    heatPumpApplication: true,
    houseNumberDecision: true,
    groundOwnership: "Openbaar (overheid)",
    contaminatedGround: "Nee",
    obstacles: "Nee",
    specialConditions: "Nee",
    existingInfrastructure: "Nee",
    dewatering: "Ja",
    dewateringBy: "Gemeente Den Haag",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Den Haag",
    phasing: "Fase 1: Woningen, Fase 2: Commercieel",
    otherPoints: "Aandacht voor duurzame energievoorziening en groene daken",
    waterGasDistance: false,
    waterSewerDistance: false,
    highPressureGasDistance: false,
    waterHeatDistance: false,
    planStatus: "In behandeling",
    designReceived: true,
    receivedDate: "2024-01-10",
    softStartWeek: "Week 5",
    hardStartWeek: "Week 8",
    trackInspection: "Gepland",
    digitalMarking: "Ja",
    storageLocation: "Gemeente Den Haag",
    risksDiscussed: "Standaard risico's besproken",
    crow500: true,
    riskExplanation: "Standaard veiligheidsmaatregelen",
    additionalComments: "Geen bijzondere opmerkingen"
  },
  {
    projectNumber: "PROJ-002",
    projectName: "Renovatie Wijk Centrum",
    projectLeader: "Lisa de Vries",
    projectType: "Reconstructie",
    meetingDate: "2024-01-20",
    meetingLocation: "Woningcorporatie Amsterdam",
    participatingUtilities: ["Liander", "Waternet", "Vattenfall"],
    otherParticipants: "Woningcorporatie Amsterdam, Aannemer",
    numberOfHouses: 18,
    numberOfApartments: 36,
    numberOfCommercialSpaces: 4,
    numberOfGeneralSpaces: 2,
    electricityReturn: true,
    largeConsumptionConnection: true,
    largeConsumptionValue: "Woningen",
    heatPumpApplication: true,
    houseNumberDecision: false,
    groundOwnership: "Particulier",
    contaminatedGround: "Ja",
    obstacles: "Ja",
    specialConditions: "Ja",
    existingInfrastructure: "Ja",
    dewatering: "Nee",
    dewateringBy: "",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Amsterdam",
    phasing: "Geleidelijke renovatie per blok",
    otherPoints: "Aandacht voor bestaande infrastructuur en bewonersoverlast",
    waterGasDistance: true,
    waterSewerDistance: true,
    highPressureGasDistance: false,
    waterHeatDistance: true,
    planStatus: "In uitvoering",
    designReceived: true,
    receivedDate: "2024-01-15",
    softStartWeek: "Week 3",
    hardStartWeek: "Week 6",
    trackInspection: "Uitgevoerd",
    digitalMarking: "Ja",
    storageLocation: "Woningcorporatie Amsterdam",
    risksDiscussed: "Specifieke risico's besproken",
    crow500: true,
    riskExplanation: "Aandacht voor bestaande infrastructuur",
    additionalComments: "Renovatie tijdens bewoning vereist extra voorzorgsmaatregelen"
  },
  {
    projectNumber: "PROJ-003",
    projectName: "Duurzame Wijk Watergraafsmeer",
    projectLeader: "Erik van Dijk",
    projectType: "Nieuwe aanleg",
    meetingDate: "2024-02-01",
    meetingLocation: "Gemeentehuis Amsterdam",
    participatingUtilities: ["Liander", "Waternet", "Eneco"],
    otherParticipants: "Gemeente Amsterdam, Duurzaamheidsadviseur",
    numberOfHouses: 50,
    numberOfApartments: 48,
    numberOfCommercialSpaces: 6,
    numberOfGeneralSpaces: 3,
    electricityReturn: true,
    largeConsumptionConnection: false,
    largeConsumptionValue: "",
    heatPumpApplication: true,
    houseNumberDecision: true,
    groundOwnership: "Openbaar (overheid)",
    contaminatedGround: "Nee",
    obstacles: "Nee",
    specialConditions: "Ja",
    existingInfrastructure: "Nee",
    dewatering: "Ja",
    dewateringBy: "Gemeente Amsterdam",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Amsterdam",
    phasing: "Fase 1: Woningen, Fase 2: Commercieel en algemeen",
    otherPoints: "Focus op energieneutraliteit en natuurinclusiviteit",
    waterGasDistance: false,
    waterSewerDistance: false,
    highPressureGasDistance: false,
    waterHeatDistance: false,
    planStatus: "Ontwerp",
    designReceived: false,
    receivedDate: "",
    softStartWeek: "Week 10",
    hardStartWeek: "Week 15",
    trackInspection: "Gepland",
    digitalMarking: "Ja",
    storageLocation: "Gemeente Amsterdam",
    risksDiscussed: "Standaard risico's besproken",
    crow500: true,
    riskExplanation: "Duurzame technologieën vereisen extra aandacht",
    additionalComments: "Energieneutrale woningen met smart grid technologie"
  },
  {
    projectNumber: "PROJ-004",
    projectName: "Herstructurering Oud-Zuid",
    projectLeader: "Marianne Smit",
    projectType: "Reconstructie",
    meetingDate: "2024-02-10",
    meetingLocation: "Woningcorporatie Rotterdam",
    participatingUtilities: ["Stedin", "Evides", "Eneco"],
    otherParticipants: "Woningcorporatie Rotterdam, Stedenbouwkundige",
    numberOfHouses: 24,
    numberOfApartments: 30,
    numberOfCommercialSpaces: 3,
    numberOfGeneralSpaces: 2,
    electricityReturn: true,
    largeConsumptionConnection: true,
    largeConsumptionValue: "Woningen",
    heatPumpApplication: true,
    houseNumberDecision: false,
    groundOwnership: "Particulier",
    contaminatedGround: "Ja",
    obstacles: "Ja",
    specialConditions: "Ja",
    existingInfrastructure: "Ja",
    dewatering: "Ja",
    dewateringBy: "Woningcorporatie Rotterdam",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Rotterdam",
    phasing: "Stapsgewijze herstructurering",
    otherPoints: "Aandacht voor historische waarden en duurzaamheid",
    waterGasDistance: true,
    waterSewerDistance: true,
    highPressureGasDistance: true,
    waterHeatDistance: true,
    planStatus: "In behandeling",
    designReceived: true,
    receivedDate: "2024-02-05",
    softStartWeek: "Week 7",
    hardStartWeek: "Week 10",
    trackInspection: "Gepland",
    digitalMarking: "Ja",
    storageLocation: "Woningcorporatie Rotterdam",
    risksDiscussed: "Specifieke risico's besproken",
    crow500: true,
    riskExplanation: "Historische waarden vereisen zorgvuldige aanpak",
    additionalComments: "Herstructurering met behoud van karakteristieke elementen"
  },
  {
    projectNumber: "PROJ-005",
    projectName: "Energieneutrale Wijk Leidsche Rijn",
    projectLeader: "Tom de Jong",
    projectType: "Nieuwe aanleg",
    meetingDate: "2024-02-15",
    meetingLocation: "Gemeentehuis Utrecht",
    participatingUtilities: ["Stedin", "Vitens", "Eneco"],
    otherParticipants: "Gemeente Utrecht, Smart Grid specialist",
    numberOfHouses: 55,
    numberOfApartments: 60,
    numberOfCommercialSpaces: 8,
    numberOfGeneralSpaces: 4,
    electricityReturn: true,
    largeConsumptionConnection: false,
    largeConsumptionValue: "",
    heatPumpApplication: true,
    houseNumberDecision: true,
    groundOwnership: "Openbaar (overheid)",
    contaminatedGround: "Nee",
    obstacles: "Nee",
    specialConditions: "Ja",
    existingInfrastructure: "Nee",
    dewatering: "Ja",
    dewateringBy: "Gemeente Utrecht",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Utrecht",
    phasing: "Fase 1: Woningen, Fase 2: Commercieel, Fase 3: Algemeen",
    otherPoints: "Smart grid technologie en energieneutraliteit centraal",
    waterGasDistance: false,
    waterSewerDistance: false,
    highPressureGasDistance: false,
    waterHeatDistance: false,
    planStatus: "Ontwerp",
    designReceived: false,
    receivedDate: "",
    softStartWeek: "Week 12",
    hardStartWeek: "Week 18",
    trackInspection: "Gepland",
    digitalMarking: "Ja",
    storageLocation: "Gemeente Utrecht",
    risksDiscussed: "Specifieke risico's besproken",
    crow500: true,
    riskExplanation: "Smart grid technologie vereist specialistische kennis",
    additionalComments: "Pilot project voor energieneutrale wijk met IoT integratie"
  },
  {
    projectNumber: "PROJ-006",
    projectName: "Transformatie Havenkwartier",
    projectLeader: "Annelies Bakker",
    projectType: "Reconstructie",
    meetingDate: "2024-02-20",
    meetingLocation: "Ontwikkelaar Havenkwartier BV",
    participatingUtilities: ["Stedin", "Evides", "Eneco"],
    otherParticipants: "Ontwikkelaar Havenkwartier BV, Milieudeskundige",
    numberOfHouses: 36,
    numberOfApartments: 42,
    numberOfCommercialSpaces: 5,
    numberOfGeneralSpaces: 3,
    electricityReturn: true,
    largeConsumptionConnection: true,
    largeConsumptionValue: "Woningen",
    heatPumpApplication: true,
    houseNumberDecision: false,
    groundOwnership: "Particulier",
    contaminatedGround: "Ja",
    obstacles: "Ja",
    specialConditions: "Ja",
    existingInfrastructure: "Ja",
    dewatering: "Ja",
    dewateringBy: "Ontwikkelaar Havenkwartier BV",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Den Haag",
    phasing: "Transformatie van industrieel naar woongebied",
    otherPoints: "Sanering van vervuilde grond en nieuwe infrastructuur",
    waterGasDistance: true,
    waterSewerDistance: true,
    highPressureGasDistance: true,
    waterHeatDistance: true,
    planStatus: "In uitvoering",
    designReceived: true,
    receivedDate: "2024-02-15",
    softStartWeek: "Week 5",
    hardStartWeek: "Week 8",
    trackInspection: "Uitgevoerd",
    digitalMarking: "Ja",
    storageLocation: "Ontwikkelaar Havenkwartier BV",
    risksDiscussed: "Specifieke risico's besproken",
    crow500: true,
    riskExplanation: "Sanering van vervuilde grond vereist speciale maatregelen",
    additionalComments: "Transformatie van industrieel gebied naar woongebied"
  },
  {
    projectNumber: "PROJ-007",
    projectName: "Circulaire Wijk Stadspark",
    projectLeader: "Femke van der Berg",
    projectType: "Nieuwe aanleg",
    meetingDate: "2024-03-01",
    meetingLocation: "Gemeentehuis Groningen",
    participatingUtilities: ["Enexis", "Waterbedrijf Groningen", "Eneco"],
    otherParticipants: "Gemeente Groningen, Circulaire economie expert",
    numberOfHouses: 33,
    numberOfApartments: 36,
    numberOfCommercialSpaces: 4,
    numberOfGeneralSpaces: 2,
    electricityReturn: true,
    largeConsumptionConnection: false,
    largeConsumptionValue: "",
    heatPumpApplication: true,
    houseNumberDecision: true,
    groundOwnership: "Openbaar (overheid)",
    contaminatedGround: "Nee",
    obstacles: "Nee",
    specialConditions: "Ja",
    existingInfrastructure: "Nee",
    dewatering: "Ja",
    dewateringBy: "Gemeente Groningen",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Groningen",
    phasing: "Fase 1: Woningen, Fase 2: Commercieel en algemeen",
    otherPoints: "Focus op circulaire materialen en hergebruik",
    waterGasDistance: false,
    waterSewerDistance: false,
    highPressureGasDistance: false,
    waterHeatDistance: false,
    planStatus: "Ontwerp",
    designReceived: false,
    receivedDate: "",
    softStartWeek: "Week 14",
    hardStartWeek: "Week 20",
    trackInspection: "Gepland",
    digitalMarking: "Ja",
    storageLocation: "Gemeente Groningen",
    risksDiscussed: "Specifieke risico's besproken",
    crow500: true,
    riskExplanation: "Circulaire materialen vereisen speciale aandacht",
    additionalComments: "Pilot project voor circulaire woonwijk"
  },
  {
    projectNumber: "PROJ-008",
    projectName: "Smart City Wijk Brainport",
    projectLeader: "Daan van der Heijden",
    projectType: "Nieuwe aanleg",
    meetingDate: "2024-03-05",
    meetingLocation: "Gemeentehuis Eindhoven",
    participatingUtilities: ["Enexis", "Brabant Water", "Eneco"],
    otherParticipants: "Gemeente Eindhoven, IoT specialist",
    numberOfHouses: 47,
    numberOfApartments: 54,
    numberOfCommercialSpaces: 6,
    numberOfGeneralSpaces: 3,
    electricityReturn: true,
    largeConsumptionConnection: false,
    largeConsumptionValue: "",
    heatPumpApplication: true,
    houseNumberDecision: true,
    groundOwnership: "Openbaar (overheid)",
    contaminatedGround: "Nee",
    obstacles: "Nee",
    specialConditions: "Ja",
    existingInfrastructure: "Nee",
    dewatering: "Ja",
    dewateringBy: "Gemeente Eindhoven",
    trafficPlans: "Ja",
    trafficFacilitiesBy: "Gemeente Eindhoven",
    phasing: "Fase 1: Woningen, Fase 2: Commercieel, Fase 3: Algemeen",
    otherPoints: "Smart city technologie en IoT integratie",
    waterGasDistance: false,
    waterSewerDistance: false,
    highPressureGasDistance: false,
    waterHeatDistance: false,
    planStatus: "Ontwerp",
    designReceived: false,
    receivedDate: "",
    softStartWeek: "Week 16",
    hardStartWeek: "Week 22",
    trackInspection: "Gepland",
    digitalMarking: "Ja",
    storageLocation: "Gemeente Eindhoven",
    risksDiscussed: "Specifieke risico's besproken",
    crow500: true,
    riskExplanation: "IoT technologie vereist specialistische kennis",
    additionalComments: "Smart city pilot project met geavanceerde technologie"
  }
];

export async function GET(
  request: NextRequest,
  { params }: { params: { projectNumber: string } }
) {
  try {
    const { projectNumber } = params;
    const d2Form = d2FormData.find(d => d.projectNumber === projectNumber);
    
    if (!d2Form) {
      return NextResponse.json({
        success: false,
        error: 'D2 form not found'
      }, { status: 404 });
    }
    
    return NextResponse.json({
      success: true,
      data: d2Form
    });
  } catch (error) {
    console.error('Error fetching D2 form:', error);
    return NextResponse.json({
      success: false,
      error: 'Failed to fetch D2 form'
    }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    const data = await request.json();
    
    // In een echte app zou je hier de data opslaan in een database
    console.log('D2 form submitted:', data);
    
    return NextResponse.json({
      success: true,
      message: 'D2 form submitted successfully'
    });
  } catch (error) {
    console.error('Error submitting D2 form:', error);
    return NextResponse.json({
      success: false,
      error: 'Failed to submit D2 form'
    }, { status: 500 });
  }
}
